[package]
name = "game_dev_rust"
version = "0.1.0"
authors = ["samyakahuja <samyak.mcs18.du@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.14"
specs-derive = "0.4"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image"]
